# Generated by Django 6.0.6 on 2026-06-07 00:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono_nequi', models.CharField(help_text='Número para pagos vía Nequi/Daviplata', max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='beneficiario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='beneficiario_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BilleteraUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo_consumo_ia', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('ganancias_acumuladas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera de Usuario',
                'verbose_name_plural': 'Billeteras de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sitio', models.CharField(max_length=100)),
                ('dominio', models.URLField(unique=True)),
                ('sub_id_afiliado', models.CharField(help_text='ID único para Amazon Associates', max_length=100, unique=True)),
                ('nicho', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('en_creacion', 'En Creación')], default='en_creacion', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portales',
            },
        ),
    ]
