# Generated by Django 6.0.6 on 2026-06-07 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('termino_busqueda', models.CharField(help_text='Ej: Zapatillas running', max_length=200)),
                ('fuente', models.CharField(help_text='Ej: Google Trends, TikTok', max_length=50)),
                ('puntuacion_viral', models.IntegerField(default=0, help_text='Score de 1 a 100')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False, help_text='¿Ya se generó contenido de esto?')),
            ],
            options={
                'verbose_name': 'Tendencia',
                'verbose_name_plural': 'Tendencias',
                'unique_together': {('termino_busqueda', 'fuente')},
            },
        ),
    ]
