# Generated by Django 6.0.6 on 2026-06-07 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0002_tendencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('contenido_html', models.TextField()),
                ('idioma', models.CharField(default='Español', max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='core_engine.portal')),
                ('tendencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_engine.tendencia')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
