# Generated by Django 6.0.6 on 2026-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0003_articulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billeterausuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tendencia',
            options={},
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('hogar', 'Hogar'), ('belleza', 'Belleza'), ('accesorios', 'Accesorios')], default='tecnologia', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_url',
            field=models.URLField(default='https://loremflickr.com/800/500/tecnologia', max_length=500),
        ),
        migrations.AddField(
            model_name='articulo',
            name='resumen',
            field=models.CharField(default='Descubre las mejores ofertas y análisis detallado de este producto.', max_length=300),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono_nequi',
            field=models.CharField(help_text='Número para pagos vía Nequi', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tendencia',
            name='fuente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tendencia',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tendencia',
            name='puntuacion_viral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tendencia',
            name='termino_busqueda',
            field=models.CharField(max_length=200),
        ),
    ]
