# Generated by Django 6.0.6 on 2026-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0004_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('hogar', 'Hogar'), ('belleza', 'Belleza'), ('moda_femenina', 'Moda Femenina')], default='tecnologia', max_length=20),
        ),
    ]
